#app.yaml Needed to configure settings of the app engine app
runtime: python39

# handlers:
#  - url: /static
#    static_dir: static
#  - url: /.*
#    script: auto


env_variables:
  DB_USER: test_user
  DB_PASS: test_password
  DB_NAME: active_vehicles
  INSTANCE_CONNECTION_NAME: starlit-oven-380019:us-east4:test-instance